import { FC } from "react";
import { Props } from './PropsLayout';
import Head from "next/head";
import { Navbar } from "../Navbar/Navbar";
import styles from "./MainLayout.module.css";

export const MainLayout: FC<Props> = ({ children }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className={styles.main}>{children}</main>
    </div>
  );
};
